### ISSUE TITLE
Not escaping `'` in `iLIKE` query properly

### ISSUE THREAD

**Issue by mieciu** [QuesmaOrg/quesma#1038]
I noticed we don't escape `'` properly. 
I found this out today when messing with filters in `eCommerce Revenue Dashboard` in OpenSearch.

Screenshot telling more than 1000s of words:

<img width="2521" alt="image" src="https://github.com/user-attachments/assets/5f429702-034a-473c-8aa0-d0325e1934ab">

**Comment by trzysiek** [comment]
Fixed with https://github.com/QuesmaOrg/quesma/pull/1114
