### ISSUE TITLE
Route all internal Kibana /_search query

### ISSUE THREAD

**Issue by jakozaur** [QuesmaOrg/quesma#373]
There are some, which are harder to detect as they use `/_search`. See method `matchAgainstKibanaInternal`

**Comment by avelanarius** [comment]
We worked around the issue by disabling the `/_search` endpoint altogether (https://github.com/QuesmaOrg/quesma/pull/559)
and during my work on proper idling I filtered out a couple of the remaining requests which prevented idling (see https://github.com/QuesmaOrg/quesma/pull/615 for example).

Therefore closing this issue for now.
