### ISSUE TITLE
Debug errors in tests

### ISSUE THREAD

**Issue by trzysiek** [QuesmaOrg/quesma#4]
All our tests pass of course, but if you initialize logger e.g. by adding `logger.InitSimpleLoggerForTests()` at the beginning of a test, you'll see a lot of errors being printed.

It's mostly with my code, so I'll try to look at it in near future.

**Comment by mieciu** [comment]
Closing a part of November '24 issue cleanup. 
Moving forwards we might look at individual errors and create a dedicated issues for them.
