### ISSUE TITLE
Airport Connections panel from Global Flight Dashboard is broken

### ISSUE THREAD

**Issue by pivovarit** [QuesmaOrg/quesma#583]
Due to `Unspecified database error` - the regression was introduced in 9c185fa8

<img width="853" alt="image" src="https://github.com/user-attachments/assets/ba34b60e-3ac7-4c95-a3ea-e4ae97d57966">

**Comment by jakozaur** [comment]
Fixed in pancake version: https://github.com/QuesmaOrg/quesma/pull/719
