### ISSUE TITLE
How to support columns with type Map

### ISSUE THREAD

**Issue by piyushfs2** [QuesmaOrg/quesma#590]
How do I search through a column which stores a map?

**Comment by jakozaur** [comment]
@piyushfs2 thanks for contacting me. It is not yet implemented. I can look into adding that tomorrow.

**Comment by jakozaur** [comment]
@piyushfs2 I did an experimental quick-fix implementation:
https://github.com/QuesmaOrg/quesma/pull/593
There, we do full-text against keys and values.

Another workaround with better performance is to use materialized columns such, see:
https://clickhouse.com/docs/knowledgebase/improve-map-performance

We are still thinking about what the default behaviour should be. What would you expect (e.g. match keys only, match value only, match both)?

We plan to evolve the schema so you can define fields visible in ElasticSearch API, even though there are just entries in the map.

Let me know your opinion.

**Comment by jakozaur** [comment]
Fixed in main:
https://github.com/QuesmaOrg/quesma/pull/593
