### ISSUE TITLE
Filter result suggestions for fields with dots don't show up

### ISSUE THREAD

**Issue by ptbrzoska** [QuesmaOrg/quesma#675]
1. discover
2. add filter
3. pick field with .
4. select is operator
5. exception pops up

<img width="957" alt="image" src="https://github.com/user-attachments/assets/cdff5aba-13b0-4ada-9fac-6524d9a48233">

1. discover
2. select field with . from KQL syntax dialog
3. select : (equals)
4. no results shown
<img width="591" alt="image" src="https://github.com/user-attachments/assets/0749675f-777b-4c13-ba98-c8d549966c3e">

**Comment by trzysiek** [comment]
Should be fixed after https://github.com/QuesmaOrg/quesma/pull/693 and https://github.com/QuesmaOrg/quesma/pull/703

**Comment by jakozaur** [comment]
We verified that fix works if type is set to `keyword` (same as in ElasticSearch).
