### ISSUE TITLE
Search error: Q3006: Unspecified database error when filtering for # values

### ISSUE THREAD

**Issue by ptbrzoska** [QuesmaOrg/quesma#863]
https://kibana-hydrolix.quesma.dev

try to filter for cacheStatus : 0 in discover

<img width="2049" alt="image" src="https://github.com/user-attachments/assets/105b4181-8a99-463e-8c69-d9c98628720a">

Stack trace:
handleSearchError@https://kibana-hydrolix.quesma.dev/68203/bundles/plugin/data/1.0.0/data.plugin.js:1:387041
search/</<@https://kibana-hydrolix.quesma.dev/68203/bundles/plugin/data/1.0.0/data.plugin.js:1:390446
a/</s<@https://kibana-hydrolix.quesma.dev/68203/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:361:795664
t/s._error<@https://kibana-hydrolix.quesma.dev/68203/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:6:36954
__kbnSharedDeps_npm__</p</t.prototype.error@https://kibana-hydrolix.quesma.dev/68203/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:361:109586
__kbnSharedDeps_npm__</u</t.prototype.error/<@https://kibana-hydrolix.quesma.dev/68203/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:351:62031
i@https://kibana-hydrolix.quesma.dev/68203/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:361:298304
__kbnSharedDeps_npm__</u</t.prototype.error@https://kibana-hydrolix.quesma.dev/68203/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:351:61898
error@https://kibana-hydrolix.quesma.dev/68203/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:361:407411
__kbnSharedDeps_npm__</h</e.prototype.error@https://kibana-hydrolix.quesma.dev/68203/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:361:110392
__kbnSharedDeps_npm__</p</t.prototype._error@https://kibana-hydrolix.quesma.dev/68203/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:361:109949
__kbnSharedDeps_npm__</p</t.prototype.error@https://kibana-hydrolix.quesma.dev/68203/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:361:109586
i@https://kibana-hydrolix.quesma.dev/68203/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:361:956095
__kbnSharedDeps_npm__</l</e.prototype._trySubscribe@https://kibana-hydrolix.quesma.dev/68203/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:294:18071
__kbnSharedDeps_npm__</l</e.prototype.subscribe/<@https://kibana-hydrolix.quesma.dev/68203/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:294:17993
i@https://kibana-hydrolix.quesma.dev/68203/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:361:298304
__kbnSharedDeps_npm__</l</e.prototype.subscribe@https://kibana-hydrolix.quesma.dev/68203/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:294:17908
a/</s<@https://kibana-hydrolix.quesma.dev/68203/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:361:795706
t/s._error<@https://kibana-hydrolix.quesma.dev/68203/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:6:36954
__kbnSharedDeps_npm__</p</t.prototype.error@https://kibana-hydrolix.quesma.dev/68203/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:361:109586
s/</<@https://kibana-hydrolix.quesma.dev/68203/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:361:814533
t/s._error<@https://kibana-hydrolix.quesma.dev/68203/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:6:36954
__kbnSharedDeps_npm__</p</t.prototype.error@https://kibana-hydrolix.quesma.dev/68203/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:361:109586
__kbnSharedDeps_npm__</p</t.prototype._error@https://kibana-hydrolix.quesma.dev/68203/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:361:109949
__kbnSharedDeps_npm__</p</t.prototype.error@https://kibana-hydrolix.quesma.dev/68203/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:361:109586
s/</<@https://kibana-hydrolix.quesma.dev/68203/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:361:814533
t/s._error<@https://kibana-hydrolix.quesma.dev/68203/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:6:36954
__kbnSharedDeps_npm__</p</t.prototype.error@https://kibana-hydrolix.quesma.dev/68203/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:361:109586
__kbnSharedDeps_npm__</p</t.prototype._error@https://kibana-hydrolix.quesma.dev/68203/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:361:109949
__kbnSharedDeps_npm__</p</t.prototype.error@https://kibana-hydrolix.quesma.dev/68203/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:361:109586
O/</<@https://kibana-hydrolix.quesma.dev/68203/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:294:8915

**Comment by ptbrzoska** [comment]
Note this may be quite old version. Didn verify on latest build.

**Comment by avelanarius** [comment]
The full error from Quesma's management console (`Illegal type UInt8 of argument of function ilike`):
```
2024-10-09 14:01:20 454017606Z
error	quesma request failed: Q3006: Unspecified database error.  clickhouse: query failed. err: code: 43, message: Illegal type UInt8 of argument of function ilike: While processing (cacheStatus ILIKE '%0%') AND ((reqTimeSec >= parseDateTime64BestEffort('2024-10-09T13:46:19.986Z')) AND (reqTimeSec <= parseDateTime64BestEffort('2024-10-09T14:01:19.986Z'))), query: SELECT "CloudWrapper_ASN", "CloudWrapper_DNSLookupTime", "CloudWrapper_GeoInfo", "CloudWrapper_IP", "CloudWrapper_RequestEndTime", "CloudWrapper_RequestID", "CloudWrapper_TurnAroundTime", "Edge_ASN", "Edge_DNSLookupTime", "Edge_GeoInfo", "Edge_IP", "Edge_RequestEndTime", "Edge_RequestID", "Edge_TurnAroundTime", "Origin_ASN", "Origin_DNSLookupTime", "Origin_GeoInfo", "Origin_IP", "Origin_IP_asn", "Origin_IP_city", "Origin_IP_country", "Origin_IP_org", "Origin_IP_subdivision1", "Origin_RequestEndTime", "Origin_RequestID", "Origin_TurnAroundTime", "Parent_ASN", "Parent_DNSLookupTime", "Parent_GeoInfo", "Parent_IP", "Parent_RequestEndTime", "Parent_RequestID", "Parent_TurnAroundTime", "Peer_ASN", "Peer_DNSLookupTime", "Peer_GeoInfo", "Peer_IP", "Peer_RequestEndTime", "Peer_RequestID", "Peer_TurnAroundTime", "UA", "accLang", "asn", "billingRegion", "breadcrumbs", "brotliStatus", "bytes", "cacheStatus", "cacheable", "city", "cliIP", "cmcd", "cmcd_buffer_length", "cmcd_buffer_starvation", "cmcd_content_id", "cmcd_deadline", "cmcd_encoded_bitrate", "cmcd_measured_throughput", "cmcd_next_object_requests", "cmcd_next_range_request", "cmcd_object_duration", "cmcd_object_type", "cmcd_playback_duration", "cmcd_playback_rate", "cmcd_requested_max_throughput", "cmcd_session_id", "cmcd_startup", "cmcd_stream_type", "cmcd_streaming_format", "cmcd_top_bitrate", "cmcd_version", "cookie", "country", "cp", "customField", "dnsLookupTimeMSec", "downloadInitiated", "downloadTime", "downloadsCompleted", "edgeAttempts", "edgeIP", "errorCode", "ewExecutionInfo", "ewUsageInfo", "fileSizeBucket", "isMidgress", "lastByte", "latency", "maxAgeSec", "objSize", "originContentLen", "overheadBytes", "prefetchMidgressHits", "proto", "queryStr", "range", "referer", "reqEndTimeMSec", "reqHost", "reqId", "reqMethod", "reqPath", "reqPort", "reqTimeSec", "rspContentLen", "rspContentType", "securityRules", "serverCountry", "startupError", "state", "statusCode", "streamId", "throughput", "timeToFirstByte", "tlsOverheadTimeMSec", "tlsVersion", "totalBytes", "transferTimeMSec", "turnAroundTimeMSec", "uncompressedSize", "unknown", "version", "xForwardedFor" FROM "akamai"."logs" WHERE ("cacheStatus" iLIKE '%0%' AND ("reqTimeSec">=parseDateTime64BestEffort('2024-10-09T13:46:19.986Z') AND "reqTimeSec"<=parseDateTime64BestEffort('2024-10-09T14:01:19.986Z'))) ORDER BY "reqTimeSec" DESC LIMIT 500: code: 43, message: Illegal type UInt8 of argument of function ilike: While processing (cacheStatus ILIKE '%0%') AND ((reqTimeSec >= parseDateTime64BestEffort('2024-10-09T13:46:19.986Z')) AND (reqTimeSec <= parseDateTime64BestEffort('2024-10-09T14:01:19.986Z')))	caller: /quesma/quesma/quesma.go:240
path: /logs/_async_search
reason: Unspecified database error.
```

**Comment by avelanarius** [comment]
> Note this may be quite old version. Didn verify on latest build.

On the management console the reported version is `Version: eap-v0.4-133-gb3af44b`

**Comment by trzysiek** [comment]
Seems already fixed on newest Quesma version.
